[project]
name = "i-love-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vanou-suerte", email = "vanessa.pech77@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "pypdf>=6.19.0",
]

[project.scripts]
i-love-pdf = "i_love_pdf.main:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"
